name: Automacao Diaria Cotação Moedas

on:
  push:
    branches:
      - cotacao
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Ativar ambiente virtual Python
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependências Python
        run: |
          pip install -r requirements.txt

      - name: Definir variável de ambiente COTA_YOUR_ACCOUNT_SID
        run: echo "COTA_YOUR_ACCOUNT_SID=confidencial" >> $GITHUB_ENV    

      - name: Executar scripts
        run: |
          run: python index.py
               python cotacao.py 
